import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import '../database/app_database.dart';

// ─────────────────────────────────────────────────────────────────────────────
// PdfExportService — Exports the investment journal to a formatted text file.
//
// Writes to the app's documents directory as:
//   viren_journal_YYYY-MM-DD.txt
//
// Uses plain text formatting because no PDF package is available.
// The output is clean, readable, and shareable via the standard
// Android share sheet.
//
// If the `pdf` package is added to pubspec in the future, replace the
// _buildTextContent method with PDF page generation.
// ─────────────────────────────────────────────────────────────────────────────

class PdfExportService {
  /// Exports starred alerts to a text file and returns the file path.
  /// Returns null if the export fails.
  static Future<String?> exportJournal(List<Alert> starredAlerts) async {
    try {
      final content = _buildTextContent(starredAlerts);

      final dir = await getApplicationDocumentsDirectory();
      final dateStr =
          DateFormat('yyyy-MM-dd').format(DateTime.now());
      final file = File('${dir.path}/viren_journal_$dateStr.txt');

      await file.writeAsString(content);
      return file.path;
    } catch (_) {
      return null;
    }
  }

  static String _buildTextContent(List<Alert> alerts) {
    final buf = StringBuffer();
    final now = DateTime.now();

    buf.writeln('VIREN — INVESTMENT JOURNAL');
    buf.writeln('Exported: ${DateFormat('dd MMMM yyyy, HH:mm').format(now)}');
    buf.writeln('Entries: ${alerts.length}');
    buf.writeln('=' * 60);
    buf.writeln();

    // Group by month
    final byMonth = <String, List<Alert>>{};
    for (final a in alerts) {
      final key = DateFormat('MMMM yyyy').format(a.createdAt);
      byMonth.putIfAbsent(key, () => []).add(a);
    }

    for (final entry in byMonth.entries) {
      buf.writeln(entry.key.toUpperCase());
      buf.writeln('-' * 40);
      buf.writeln();

      for (final alert in entry.value) {
        final date = DateFormat('dd MMM yyyy, HH:mm').format(alert.createdAt);
        final type = alert.alertType.replaceAll('_', ' ');
        final symbol = alert.relatedInstrument ?? 'PORTFOLIO';

        buf.writeln('[$type] $symbol');
        buf.writeln('Date:    $date');
        buf.writeln('Signal:  ${alert.title}');
        buf.writeln('Detail:  ${alert.description}');
        if (alert.confidence > 0) {
          buf.writeln('Confidence: ${alert.confidence}%');
        }
        buf.writeln();
      }
    }

    buf.writeln('=' * 60);
    buf.writeln('Generated by Viren — Private. Local. Yours.');

    return buf.toString();
  }
}
