// ─────────────────────────────────────────────────────────────────────────────
// AI Provider — Abstract Interface for AI Assistance
//
// Level 1 ONLY (narrator/explainer). AI may:
//   • Explain existing alerts generated by rule engines
//   • Summarize portfolio state from already-computed statistics
//   • Reflect on user behavior patterns already detected
//   • Convert numerical insights into natural language
//
// AI MUST NOT: predict prices, suggest trades, optimize profit, manipulate
// emotion, invent insights, or introduce new facts.
//
// The system MUST remain fully functional if AI is removed.
// AI is user-invoked (button-triggered), never automatic.
// AI is disable-able via a single settings toggle.
// ─────────────────────────────────────────────────────────────────────────────

/// Response from an AI operation.
class AiResponse {
  /// The generated natural language content.
  final String content;

  /// Citations pointing to deterministic data sources.
  /// Every output must have at least one citation.
  final List<String> citations;

  /// Whether this output is explainable (must be true to display).
  final bool isExplainable;

  /// Metadata about the generation.
  final Map<String, dynamic> metadata;

  const AiResponse({
    required this.content,
    required this.citations,
    required this.isExplainable,
    this.metadata = const {},
  });
}

/// Sanitized portfolio data safe for AI consumption.
/// Never contains raw trades, prices, emotions, or encryption material.
class SanitizedPortfolioData {
  final int totalHoldings;
  final double totalInvestedPercent; // normalized, not absolute
  final Map<String, double> allocationPercents; // symbol → %
  final double confidenceScore;
  final String timeRange; // e.g. "Jan 2024 – Feb 2025"
  final Map<String, dynamic> aggregateStats;

  const SanitizedPortfolioData({
    required this.totalHoldings,
    required this.totalInvestedPercent,
    required this.allocationPercents,
    required this.confidenceScore,
    required this.timeRange,
    required this.aggregateStats,
  });
}

/// Sanitized behavior data for AI reflection.
class SanitizedBehaviorData {
  final double tradesPerMonth;
  final double buyToSellRatio;
  final double consistencyScore;
  final double strategyAdherenceScore;
  final double emotionalStabilityScore;
  final int inactivityDays;

  const SanitizedBehaviorData({
    required this.tradesPerMonth,
    required this.buyToSellRatio,
    required this.consistencyScore,
    required this.strategyAdherenceScore,
    required this.emotionalStabilityScore,
    required this.inactivityDays,
  });
}

/// Sanitized insight data for AI explanation.
class SanitizedInsightData {
  final String ruleId;
  final String alertTitle;
  final Map<String, dynamic> triggerData;
  final int confidence;

  const SanitizedInsightData({
    required this.ruleId,
    required this.alertTitle,
    required this.triggerData,
    required this.confidence,
  });
}

/// Abstract AI provider interface.
///
/// Implementations may use:
///   • Local on-device inference (small models)
///   • Self-hosted inference server
///   • Optional cloud inference (opt-in only)
///
/// The system must work without ANY implementation of this interface.
abstract class AiProvider {
  /// Whether this AI provider is currently available and enabled.
  bool get isAvailable;

  /// Summarizes the current portfolio state in natural language.
  Future<AiResponse> summarize(SanitizedPortfolioData data);

  /// Reflects on user's behavioral patterns.
  Future<AiResponse> reflect(SanitizedBehaviorData data);

  /// Explains a specific alert/insight in plain language.
  Future<AiResponse> explain(SanitizedInsightData data);
}

/// No-op AI provider — returns empty responses.
/// Used when AI is disabled or no provider is configured.
class DisabledAiProvider extends AiProvider {
  @override
  bool get isAvailable => false;

  @override
  Future<AiResponse> summarize(SanitizedPortfolioData data) async {
    return const AiResponse(
      content: '',
      citations: [],
      isExplainable: false,
    );
  }

  @override
  Future<AiResponse> reflect(SanitizedBehaviorData data) async {
    return const AiResponse(
      content: '',
      citations: [],
      isExplainable: false,
    );
  }

  @override
  Future<AiResponse> explain(SanitizedInsightData data) async {
    return const AiResponse(
      content: '',
      citations: [],
      isExplainable: false,
    );
  }
}
